/**
 * Adversarial fixtures (fixtures/hard/, generated by `npm run fixtures:hard`).
 *
 * One file per class of real-world pollution, each with an `expected.json` that
 * states three things:
 *   1. droppedLines — how many non-empty lines cleaning must remove ([min, max])
 *   2. mustKeep     — story sentences that must survive
 *   3. mustNotTop   — words that must NOT appear in the TOP 40
 *
 * The expectations describe what a *correct* reader would do, not what the
 * current cleaner happens to do. Failures here are a coverage report, not a
 * reason to loosen the expectation — see notes/docs/32.
 */
import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { analyze, DEFAULT_ANALYZE_OPTIONS } from '../src/core/analyze';
import { parseChatFile } from '../src/core/parse';
import type { Role } from '../src/core/types';

interface Expected {
  id: string;
  title: string;
  roles: Role[];
  droppedLines: [number, number];
  mustKeep: string[];
  mustNotTop: string[];
  why: string;
}

const DIR = path.join(process.cwd(), 'fixtures', 'hard');
const ids = fs.existsSync(DIR)
  ? fs.readdirSync(DIR).filter((f) => f.endsWith('.expected.json')).map((f) => f.replace('.expected.json', '')).sort()
  : [];

if (ids.length === 0) {
  console.log('[hard-fixtures] fixtures/hard 不存在，跳过。生成：npm run fixtures:hard');
}

const nonEmpty = (s: string) => s.split('\n').filter((l) => l.trim()).length;

/**
 * These fixtures measure how much plugin noise the cleaner still lets through. Some gaps are
 * known and tracked in notes/docs/32, so a single miss must not turn the whole suite red —
 * instead every miss is recorded and the run fails only if the total grows past the ratchet
 * below. Lower the number whenever a gap is closed; never raise it without saying why.
 */
const MAX_MISSES = 5;
const misses: string[] = [];
const soft = (label: string, check: () => void) => { try { check(); } catch (e) { misses.push(`${label}: ${(e as Error).message.split('\n')[0]}`); } };

describe.skipIf(ids.length === 0)('脏聊天记录夹具', () => {
  for (const id of ids) {
    const exp = JSON.parse(fs.readFileSync(path.join(DIR, `${id}.expected.json`), 'utf8')) as Expected;
    const content = fs.readFileSync(path.join(DIR, `${id}.jsonl`), 'utf8');
    const roles = exp.roles;

    describe(`${exp.id} ${exp.title}`, () => {
      const chat = parseChatFile(`${id}.jsonl`, content, {
        clean: DEFAULT_ANALYZE_OPTIONS.clean,
        includeAllSwipes: false,
      });
      const counted = chat.messages.filter((m) => roles.includes(m.role));
      const dropped = counted.reduce((a, m) => a + nonEmpty(m.raw) - nonEmpty(m.text), 0);
      const cleanedAll = counted.map((m) => m.text).join('\n');
      const result = analyze([{ name: `${id}.jsonl`, content }], { ...DEFAULT_ANALYZE_OPTIONS, roles });
      const top = result.words.slice(0, 40).map((w) => w.text);

      it('文件本身可解析，没有警告', () => {
        expect(chat.warnings).toEqual([]);
        expect(counted.length).toBeGreaterThan(8);
      });

      it(`清掉的行数落在 [${exp.droppedLines[0]}, ${exp.droppedLines[1]}]（实际 ${dropped}）`, () => {
        soft(`${exp.id} dropped=${dropped}`, () => {
          expect(dropped).toBeGreaterThanOrEqual(exp.droppedLines[0]);
          expect(dropped).toBeLessThanOrEqual(exp.droppedLines[1]);
        });
      });

      it('关键正文没有被误删', () => {
        const missing = exp.mustKeep.filter((s) => !cleanedAll.includes(s));
        expect(missing).toEqual([]);
      });

      it.skipIf(exp.mustNotTop.length === 0)('TOP 40 里没有噪声词', () => {
        const lower = top.map((t) => t.toLowerCase());
        const hits = exp.mustNotTop.filter((w) => lower.includes(w.toLowerCase()));
        soft(`${exp.id} 泄漏 ${hits.join(' ')}`, () => expect(hits).toEqual([]));
      });
    });
  }

  it(`未闭合的清洗缺口不超过 ${MAX_MISSES} 条`, () => {
    if (misses.length) console.log('清洗缺口：\n  ' + misses.join('\n  '));
    expect(misses.length).toBeLessThanOrEqual(MAX_MISSES);
  });
});
